### ISSUE TITLE
change the core team images and their roles

### ISSUE THREAD

**Issue by mahakmakharia** [dsc-iem/Website#25]

**Comment by AnirbanB02** [comment]
Can you please assign this task to me? So that I can start working on it, asap..

**Comment by mahakmakharia** [comment]
Yes, sure! That'll be great.

You can find the core team member names and other details here https://docs.google.com/spreadsheets/d/1FzyhEYA_7ggyGtFOob2QXGuNZUn_Wz8BznOhDXcAbuQ/edit?usp=sharing

Their images are here: https://drive.google.com/drive/folders/16APrMeD42JsCkYwN7QeeI_5WGMZ5I6sU?usp=sharing

**Comment by AnirbanB02** [comment]
Thank You!! It means a lot. I won't be disappointing you

**Comment by AnirbanB02** [comment]
May I know a little bit more about Aneesh Kar? I need it to add to the back side of the card

**Comment by mahakmakharia** [comment]
I've updated all the blank fields now!

**Comment by AnirbanB02** [comment]
Yeps!. I've complete the task. I'll make PR after 1st Oct. May I work on a different issue now?

**Comment by mahakmakharia** [comment]
first, can you pleasen share screenshots of the changes you've done in the discord channel?

**Comment by AnirbanB02** [comment]
Since there are a lot of Screenshots so I'm sharing the GDrive link of the shots. 
Google Drive: https://drive.google.com/drive/folders/1mKViOmldEiN4M_gPcy6NNkpuCVuF912R?usp=sharing
If you further want me, to share these via discord, please ask, I'll definitely do it.

**Comment by mahakmakharia** [comment]
Looks good, just change Aneesh's bio, it was updated a little late. Good work!

**Comment by AnirbanB02** [comment]
Thank You!! Didi.
But,
"Management is his middle name!" This is what I found in the sheet, about Aneesh Da, I've copied the same in the website. Can you please check it again? If it's different please let me know.

**Comment by mahakmakharia** [comment]
Full-stack web and mobile application development enthusiast whose also a graphics designer and has managed several events!

Use this for Aneesh.

Thanks!

**Comment by ommiy2j** [comment]
Can you please assign me this ......

**Comment by mahakmakharia** [comment]
hey @ommiy2j Anirban has already worked on it, so can't assign you this :)

**Comment by mahakmakharia** [comment]
@AnirbanB02 You've done a good job, the changes are live on the site! Thank you for putting in the effort to do it :)

**Comment by AnirbanB02** [comment]
Thank you Di!!
