### ISSUE TITLE
Create a new section for registering mentors in index.html

### ISSUE THREAD

**Issue by mahakmakharia** [dsc-iem/Website#30]
Add a new section where it will have these details:

Heading: Would you like to mentor us?

1. A relevant image for mentors/alumni
2. Space for some description
3. A button which will redirect to the form bit.ly/dsciemma

**Comment by aritropc** [comment]
May I get the opportunity to create the section for registering mentors?

**Comment by mahakmakharia** [comment]
Sure, go ahead!

**Comment by ommiy2j** [comment]
hey @mahakmakharia  can you please assign this issue..........

**Comment by mahakmakharia** [comment]
it's already assigned to someone else
